##############################################################
#
# Here are some things you might want to configure
#
##############################################################

include ../../miami.config


all clean cleanall info:
	@make -f makefile.pin $@ PIN_ROOT=$(PIN_HOME) 
