
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[483] =
    {   0,
      103,  103,  100,  100,  108,  106,  104,  105,  103,  106,
      106,  106,   81,   82,   87,   86,   78,  106,  106,   96,
       96,   76,   77,   74,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   79,   80,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   83,   75,   84,
      101,  100,   99,  101,  104,  103,    0,   93,   95,    0,
       85,   88,   98,    0,   96,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   22,   94,   94,
       94,   94,   94,   94,   94,   94,  100,  102,   95,   92,
       97,   97,   97,   97,   94,   94,   45,   94,   94,   94,
       44,   94,   94,   94,   50,   94,   94,   94,   94,   94,
       94,   94,   46,   94,   94,   94,   94,   94,   94,   94,
       94,   56,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   48,   94,   94,   94,
       94,   94,   94,   53,   94,   94,   14,   94,   94,   23,
       94,   94,   94,   17,   94,   97,   97,   97,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   38,   94,   94,
       94,   58,   94,   94,   94,   94,   34,   26,   94,   94,
       94,   94,   43,   39,   49,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   59,   94,   94,   51,   94,
       31,   94,   94,   94,   94,   69,   94,   94,   13,   94,
       94,   94,   94,    9,   94,   94,   47,   94,   42,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   55,
       94,   60,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   15,   94,   94,   94,   94,
       94,   94,   94,   67,   94,   94,   94,   94,   94,   94,
       94,   94,   40,   94,   94,   63,   94,   94,   94,   94,
       94,   94,   94,   35,   71,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   18,   94,   94,   94,   94,
       70,   94,   36,   94,   68,   94,   94,   94,   94,   94,
       94,   94,    4,   10,   94,   94,   52,   89,   94,   94,
       94,   94,   94,    8,   94,   94,   41,   94,   94,   94,
        5,   94,   94,   19,   94,   16,   94,   94,   94,   94,
       94,   94,    1,   73,   94,   94,   94,   27,   94,   94,

       94,   94,   64,   94,   57,   94,   94,   94,   72,   94,
       94,   94,   94,   94,   94,    7,   90,   94,   94,   94,
       94,   24,   94,   94,   28,   54,   94,   94,   65,   94,
       94,   94,   61,   94,   62,   94,   94,   94,   94,   94,
       33,   94,   94,   94,   94,   94,   94,   66,   11,   94,
       12,   94,   94,   94,   94,   37,    6,   94,   29,   94,
       94,   94,   94,   21,   94,   94,   94,   94,   30,   32,
       94,   94,   94,   25,   94,   20,   94,    2,   94,   91,
        3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,    1,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   40,   41,   42,   43,   44,   45,   32,
       46,    1,   47,    1,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   32,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   73,   74,   75,   76,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[77] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    4,    1,    5,    5,    1,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    7,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[490] =
    {   0,
        0,    0,   75,   77,  551,  552,  548,  552,  545,  543,
        0,    0,  552,  552,  552,  536,  552,  525,  535,  530,
       67,  552,  552,  552,   53,   23,   29,  486,  471,  473,
      487,    0,  478,  470,   64,   44,  501,   34,   41,   54,
      471,  474,  481,  476,   47,  552,  552,  480,  469,   51,
      467,  468,  479,  474,  473,  472,  467,  552,  552,  552,
      552,  521,  552,  507,  519,  516,  514,  552,    0,  511,
      552,  552,  552,  107,  111,    0,  484,  471,  463,  442,
      460,  449,  448,   39,  442,  440,  441,  446,  439,   68,
      445,  482,   62,   69,  443,  436,  432,  441,   99,   67,

       51,   80,  432,  431,   80,  432,  434,  445,  445,   87,
      428,  431,  435,  425,  437,  427,  422,    0,  424,  437,
      417,  416,  422,  421,  429,  412,  476,  552,    0,  552,
      552,  125,  133,  141,  429,  428,  451,  413,  412,  423,
      427,   92,  398,  428,    0,  403,  416,  439,  412,  100,
      399,  400,    0,  410,  404,  404,  402,  396,  406,  403,
      388,    0,  425,  429,  385,  397,  381,  392,  389,   98,
      398,  419,  391,  390,  376,  377,    0,  378,  378,  378,
      372,  385,  381,    0,  370,  367,    0,  373,  367,    0,
      378,  368,  366,    0,  372,  146,  148,  152,  386,  396,

      401,  373,  371,  356,  370,  397,  366,    0,  357,  368,
      349,    0,  350,  349,  348,  355,    0,  132,  360,  353,
      349,  343,    0,  383,  384,  375,  343,  132,  350,  345,
      338,  351,  334,  333,  330,    0,  329,  341,    0,  341,
        0,  332,  330,  334,  328,    0,  341,  323,    0,  334,
      325,  320,  325,    0,  348,  347,    0,  343,    0,  314,
      323,  313,  312,  319,  324,  317,  340,  305,  303,  309,
      307,  301,  318,  305,  297,  292,  339,  310,  326,  293,
      306,  293,  290,  297,  290,  303,  300,  291,  298,    0,
      291,  325,  296,  277,  284,  275,  279,  281,  287,  290,

      268,  290,  308,  298,  283,    0,  280,  285,  266,  265,
      264,  268,  267,    0,  277,  261,  265,  263,  265,  270,
      262,  147,    0,  269,  292,    0,  270,  261,  266,  263,
      253,  261,  275,    0,  288,  258,  248,  286,  247,  246,
      267,  252,  245,  246,  230,    0,  234,  260,  259,  232,
        0,  236,  259,  229,    0,  233,  231,  225,  234,  236,
      224,  252,    0,    0,  234,  229,    0,    0,  233,  217,
      227,  227,  230,    0,  231,  255,    0,  217,  212,  240,
        0,  218,  219,    0,  207,    0,  219,  232,  232,  207,
      217,  202,    0,    0,  203,  208,  213,    0,  210,  199,

      200,  207,    0,  206,    0,  205,  208,  189,    0,  201,
      205,  190,  179,  194,  183,    0,    0,  208,  180,  191,
      193,    0,  183,  220,    0,    0,  192,  177,    0,  189,
      181,  186,    0,  177,    0,  184,  170,  182,  210,  168,
        0,  178,  155,  166,  155,  149,  161,    0,    0,  145,
        0,  128,  129,  153,  141,    0,    0,  132,    0,  125,
      126,  132,  134,    0,  155,  131,  124,  131,    0,    0,
      116,  144,  113,    0,  121,    0,  138,    0,   74,    0,
        0,  552,  199,  206,  109,  213,  216,  219,  225
    } ;

static yyconst flex_int16_t yy_def[490] =
    {   0,
      482,    1,  483,  483,  482,  482,  482,  482,  482,  484,
      485,  486,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  482,  482,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  484,  482,  488,  482,
      482,  482,  482,  489,  482,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  482,  482,  488,  482,
      482,  489,  489,  489,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  489,  489,  489,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,    0,  482,  482,  482,  482,  482,  482,  482
    } ;

static yyconst flex_int16_t yy_nxt[629] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,    6,   19,   20,   21,   22,   23,   24,
        6,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   32,   35,   36,   37,   32,   38,   39,   40,   41,
       42,   43,   44,   45,   32,   46,   47,   32,   48,   32,
       49,   32,   32,   50,   51,   32,   52,   32,   53,   54,
       32,   32,   32,   32,   32,   32,   55,   32,   56,   57,
       32,   32,   32,   58,   59,   60,   62,   63,   62,   63,
       74,   81,   75,   75,   64,   77,   64,   78,   83,   92,
       84,   85,   94,  102,   82,  100,   95,  113,  101,  142,

       96,  143,  103,  166,   79,   97,  104,  167,  114,  105,
      154,   98,  117,  118,   69,  119,  155,  106,   80,  156,
      107,  108,  132,  133,   74,   93,   75,   75,  149,  164,
      168,  165,  134,  150,  151,  162,  173,  179,  163,  157,
      132,  133,  169,  206,  180,  481,  170,  174,  196,  196,
      134,  197,  214,  197,  233,  271,  198,  198,  134,  134,
      207,  196,  196,  198,  198,  234,  215,  198,  198,  281,
      272,  134,  480,  365,  282,  366,  479,  134,  478,  477,
      476,  475,  474,  473,  472,  134,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  134,   61,

       61,   61,   61,   61,   61,   61,   67,  459,   67,   67,
       67,   67,   67,   70,  458,  457,   70,   70,   70,   70,
       76,   76,   76,  129,  129,  131,  131,  131,  456,  131,
      131,  131,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,

      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,

      285,  284,  283,  280,  279,  278,  277,  276,  275,  274,
      273,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  213,  212,  211,  210,  209,  208,
      205,  204,  203,  202,  201,  200,  199,  127,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  178,  177,  176,  175,  172,  171,  161,

      160,  159,  158,  153,  152,  148,  147,  146,  145,  144,
      141,  140,  139,  138,  137,  136,  135,  130,   68,   66,
       65,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      116,  115,  112,  111,  110,  109,   99,   91,   90,   89,
       88,   87,   86,   74,   73,   72,   71,   68,   66,   65,
      482,    5,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482
    } ;

static yyconst flex_int16_t yy_chk[629] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
       21,   26,   21,   21,    3,   25,    4,   25,   27,   35,
       27,   27,   36,   39,   26,   38,   36,   45,   38,   84,

       36,   84,   39,  101,   25,   36,   40,  101,   45,   40,
       93,   36,   50,   50,  485,   50,   93,   40,   25,   94,
       40,   40,   74,   74,   75,   35,   75,   75,   90,  100,
      102,  100,   74,   90,   90,   99,  105,  110,   99,   94,
      132,  132,  102,  142,  110,  479,  102,  105,  133,  133,
      132,  134,  150,  134,  170,  218,  134,  134,  133,   74,
      142,  196,  196,  197,  197,  170,  150,  198,  198,  228,
      218,  196,  477,  322,  228,  322,  475,  132,  473,  472,
      471,  468,  467,  466,  465,  133,  463,  462,  461,  460,
      458,  455,  454,  453,  452,  450,  447,  446,  196,  483,

      483,  483,  483,  483,  483,  483,  484,  445,  484,  484,
      484,  484,  484,  486,  444,  443,  486,  486,  486,  486,
      487,  487,  487,  488,  488,  489,  489,  489,  442,  489,
      489,  489,  440,  439,  438,  437,  436,  434,  432,  431,
      430,  428,  427,  424,  423,  421,  420,  419,  418,  415,
      414,  413,  412,  411,  410,  408,  407,  406,  404,  402,
      401,  400,  399,  397,  396,  395,  392,  391,  390,  389,
      388,  387,  385,  383,  382,  380,  379,  378,  376,  375,
      373,  372,  371,  370,  369,  366,  365,  362,  361,  360,
      359,  358,  357,  356,  354,  353,  352,  350,  349,  348,

      347,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  333,  332,  331,  330,  329,  328,  327,  325,
      324,  321,  320,  319,  318,  317,  316,  315,  313,  312,
      311,  310,  309,  308,  307,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      258,  256,  255,  253,  252,  251,  250,  248,  247,  245,
      244,  243,  242,  240,  238,  237,  235,  234,  233,  232,

      231,  230,  229,  227,  226,  225,  224,  222,  221,  220,
      219,  216,  215,  214,  213,  211,  210,  209,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  195,  193,  192,
      191,  189,  188,  186,  185,  183,  182,  181,  180,  179,
      178,  176,  175,  174,  173,  172,  171,  169,  168,  167,
      166,  165,  164,  163,  161,  160,  159,  158,  157,  156,
      155,  154,  152,  151,  149,  148,  147,  146,  144,  143,
      141,  140,  139,  138,  137,  136,  135,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  117,  116,  115,  114,
      113,  112,  111,  109,  108,  107,  106,  104,  103,   98,

       97,   96,   95,   92,   91,   89,   88,   87,   86,   85,
       83,   82,   81,   80,   79,   78,   77,   70,   67,   66,
       65,   64,   62,   57,   56,   55,   54,   53,   52,   51,
       49,   48,   44,   43,   42,   41,   37,   34,   33,   31,
       30,   29,   28,   20,   19,   18,   16,   10,    9,    7,
        5,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "machine_description.l"
#line 5 "machine_description.l"
/*
 * This file is part of the MIAMI framework. For copyright information, see
 * the LICENSE file in the MIAMI root folder.
 */
/* 
 * File: machine_description.l
 * Author: Gabriel Marin, mgabi99@gmail.com
 *
 * Description: The lex parser for the MIAMI Machine Description Language.
 */

#include <stdlib.h>
#include <unistd.h>
#include <strings.h>

#include "instr_bins.H"
#include "instr_info.H"
#include "position.h"
#include "Machine.h"
#include "BitSet.h"
#include "InstTemplate.h"
#include "Instruction.h"
#include "GenericInstruction.h"

using namespace MIAMI;
#include "machdesc.tab.h"

/*#undef yywrap; */
#define TAB_WIDTH 8

namespace MIAMI
{

Position currentPosition;
int haveErrors = 0;
}

#line 787 "<stdout>"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 46 "machine_description.l"


#line 973 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 483 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 552 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "machine_description.l"
{ currentPosition += yyleng; return T_CPU_UNITS; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "machine_description.l"
{ currentPosition += yyleng; return T_ASYNC_RESOURCES; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "machine_description.l"
{ currentPosition += yyleng; return T_MEMORY_HIERARCHY; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "machine_description.l"
{ currentPosition += yyleng; return T_MACHINE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "machine_description.l"
{ currentPosition += yyleng; return T_VERSION; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "machine_description.l"
{ currentPosition += yyleng; return T_INSTRUCTION; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "machine_description.l"
{ currentPosition += yyleng; return T_TEMPLATE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "machine_description.l"
{ currentPosition += yyleng; return T_REPLACE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "machine_description.l"
{ currentPosition += yyleng; return T_WITH; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "machine_description.l"
{ currentPosition += yyleng; return T_MAXIMUM; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 58 "machine_description.l"
{ currentPosition += yyleng; return T_RETIRE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "machine_description.l"
{ currentPosition += yyleng; return T_WINDOW_SIZE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "machine_description.l"
{ currentPosition += yyleng; return T_FROM; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "machine_description.l"
{ currentPosition += yyleng; return T_FOR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "machine_description.l"
{ currentPosition += yyleng; return T_BYPASS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "machine_description.l"
{ currentPosition += yyleng; return T_LATENCY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "machine_description.l"
{ currentPosition += yyleng; return T_VECTOR_UNIT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = MEMORY_TYPE; return T_DEPENDENCY_TYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = CONTROL_TYPE; return T_DEPENDENCY_TYPE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = ADDR_REGISTER_TYPE; return T_DEPENDENCY_TYPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = GP_REGISTER_TYPE; return T_DEPENDENCY_TYPE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = ExecUnitType_FP; return T_UNIT_TYPE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = ExecUnitType_INT; return T_UNIT_TYPE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_inner_loop; return T_INST_TYPE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_intrinsic; return T_INST_TYPE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_load; return T_INST_TYPE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_load_conf; return T_INST_TYPE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_load_store; return T_INST_TYPE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_mem_fence; return T_INST_TYPE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_privl_op; return T_INST_TYPE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 94 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_trap; return T_INST_TYPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_branch; return T_INST_TYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_br_CC; return T_INST_TYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_jump; return T_INST_TYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 102 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_ret; return T_INST_TYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_cvt; return T_INST_TYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_cvt_prec; return T_INST_TYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 108 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_copy; return T_INST_TYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_move; return T_INST_TYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_move_cc; return T_INST_TYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 114 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_shuffle; return T_INST_TYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_blend; return T_INST_TYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 118 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_misc; return T_INST_TYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_cmp; return T_INST_TYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_add; return T_INST_TYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 124 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_lea; return T_INST_TYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_add_cc; return T_INST_TYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 128 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_sub; return T_INST_TYPE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 130 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_mult; return T_INST_TYPE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_div; return T_INST_TYPE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 134 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_sqrt; return T_INST_TYPE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 136 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_madd; return T_INST_TYPE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 138 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_xor; return T_INST_TYPE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 140 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_logical; return T_INST_TYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 142 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_shift; return T_INST_TYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_nop; return T_INST_TYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_prefetch; return T_INST_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 148 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_getf; return T_INST_TYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 150 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_setf; return T_INST_TYPE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 152 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_store; return T_INST_TYPE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 154 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_store_conf; return T_INST_TYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 156 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_unknown; return T_INST_TYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 158 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_popcnt; return T_INST_TYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 160 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_port_rd; return T_INST_TYPE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 162 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_port_wr; return T_INST_TYPE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 164 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_reciprocal; return T_INST_TYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 166 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_insert; return T_INST_TYPE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 168 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_extract; return T_INST_TYPE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 170 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_xchg; return T_INST_TYPE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 172 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_cmp_xchg; return T_INST_TYPE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 174 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_rotate; return T_INST_TYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 176 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_rotate_cc; return T_INST_TYPE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 178 "machine_description.l"
{ currentPosition += yyleng; 
                  yylval.int_value = IB_fn; return T_INST_TYPE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 182 "machine_description.l"
{ currentPosition += yyleng; return T_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 183 "machine_description.l"
{ currentPosition += yyleng; return T_OR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 184 "machine_description.l"
{ currentPosition += yyleng; return T_COLON; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 185 "machine_description.l"
{ currentPosition += yyleng; return T_SEMICOLON; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 186 "machine_description.l"
{ currentPosition += yyleng; return T_COMMA; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 187 "machine_description.l"
{ currentPosition += yyleng; return T_LBRACKET; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 188 "machine_description.l"
{ currentPosition += yyleng; return T_RBRACKET; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 189 "machine_description.l"
{ currentPosition += yyleng; return T_LPAREN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 190 "machine_description.l"
{ currentPosition += yyleng; return T_RPAREN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 191 "machine_description.l"
{ currentPosition += yyleng; return T_LCPAREN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 192 "machine_description.l"
{ currentPosition += yyleng; return T_RCPAREN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "machine_description.l"
{ currentPosition += yyleng; return T_PLUSPLUS; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 194 "machine_description.l"
{ currentPosition += yyleng; return T_PLUS; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 195 "machine_description.l"
{ currentPosition += yyleng; return T_TIMES; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 196 "machine_description.l"
{ currentPosition += yyleng; return T_ARROW; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "machine_description.l"
{ currentPosition += yyleng; return T_NOTHING; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 199 "machine_description.l"
{ currentPosition += yyleng; return T_ALL_UNITS; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 200 "machine_description.l"
{ currentPosition += yyleng; return T_ANY_INSTRUCTION; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 202 "machine_description.l"
{ currentPosition += yyleng;
                               yylval.ch_value = yytext[1];
                               return T_CHAR_CONST; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 205 "machine_description.l"
{ currentPosition += yyleng; 
                               yylval.p_char = new char[yyleng-1];
                               strncpy(yylval.p_char, yytext+1, yyleng-2);
                               yylval.p_char[yyleng-2] = 0;
                               return T_STR_CONST; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 210 "machine_description.l"
{ currentPosition += yyleng; 
                               yylval.p_char = new char[yyleng+1];
                               strcpy(yylval.p_char, yytext);
                               return T_IDENTIFIER; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 214 "machine_description.l"
{ currentPosition += yyleng; 
                               yylval.p_char = new char[yyleng];
                               strcpy(yylval.p_char, yytext+1);
                               return T_GP_REG_NAME; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 219 "machine_description.l"
{ currentPosition += yyleng; 
                               yylval.int_value = atoi(yytext);
                               return T_INT_CONST; }
	YY_BREAK
case 97:
/* rule 97 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 223 "machine_description.l"
{ currentPosition += yyleng;
                                                          yylval.fl_value = atof(yytext);
                                                          return T_FLOAT_CONST; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 227 "machine_description.l"
{ currentPosition += yyleng;
                               BEGIN comment;
                             }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 230 "machine_description.l"
{ currentPosition++; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 231 "machine_description.l"
{ currentPosition.tab(TAB_WIDTH, yyleng); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 232 "machine_description.l"
{ currentPosition += yyleng; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 233 "machine_description.l"
{ currentPosition += yyleng;
                               BEGIN INITIAL;
                             }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 236 "machine_description.l"
{ currentPosition += yyleng; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 237 "machine_description.l"
{ currentPosition.tab(TAB_WIDTH, yyleng); }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 238 "machine_description.l"
{ currentPosition++; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 240 "machine_description.l"
{  
           haveErrors += 1;
           fprintf(stderr, "Error %d: File %s (%d,%d): illegal characters '%s'.\n", 
               haveErrors, currentPosition.FileName(), 
               currentPosition.Line(), currentPosition.Column(), yytext);
           currentPosition += yyleng;
         }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 248 "machine_description.l"
ECHO;
	YY_BREAK
#line 1679 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 483 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 483 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 482);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 248 "machine_description.l"



int
yywrap()
{
  return 1;
}


