##############################################################
#
# Here are some things you might want to configure
#
##############################################################

include ../../miami.config
#PIN_ROOT = $(HOME)

all clean cleanall info:
	#ozgurS removing PIN_ROOT
	#@make -f makefile.pin $@ PIN_ROOT=$(PIN_ROOT) 
	#ozgurE
	@make -f makefile.pin $@ PIN_ROOT="/people/kili239"
