#!/bin/bash

commonPrefix=""
prefixLen=0
i=0
exedir=`dirname $0`

#echo -n "Processing file "
while read line
do
#   line=`${exedir}/canonicalize ${line}`
   line=`dirname ${line}`
   line=`echo "@#$"${line} | sed -e "s/ /%@/g"`
   if test $i -eq 0
   then
      commonPrefix=${line}
      prefixLen=`echo ${commonPrefix} | tr "/" " " | wc -w | tr -d " "`
   else
      line1=`echo ${commonPrefix} | tr "/" " " | sed -e "s/^[ \t]*//g"`
      line2=`echo ${line} | tr "/" " " |  sed -e "s/^[ \t]*//g"`
      line2len=`echo ${line2} | tr "/" " " | wc -w | tr -d " "`
      minlen=${prefixLen}
      if test ${line2len} -lt ${minlen}
      then
         minlen=${line2len}
      fi
      
      j=0
      while test ${j} -lt ${minlen}
      do
         f=`expr ${j} + 1`
         str1=`echo ${line1} | cut -d" " -f${f}`
         str2=`echo ${line2} | cut -d" " -f${f}`
         if test "${str1}" != "${str2}"
         then
            break
         fi
         j=`expr ${j} + 1`
      done
#      echo "Partial common prefix len = ${j}"
      prefixLen=${j}
      if test ${j} -eq 0
      then
         commonPrefix=""
         break
      else
         commonPrefix=`echo ${commonPrefix} | cut -d"/" -f-${j}`
#         echo -n "."
#         echo "Partial common prefix: >${commonPrefix}<"
      fi
   fi
   
   i=`expr ${i} + 1`
done;

truePrefix=`echo ${commonPrefix} | sed -e "s/^@#\$\(.\)/\1/g" -e "s/%@/ /g"`
#echo
#echo "Common prefix is \"${commonPrefix}\""
#echo "True prefix is \"${truePrefix}\""
echo ${truePrefix}
