#!/bin/bash
# -*- mode: sh -*-

#*BeginPNNLCopyright*********************************************************
#
# $HeadURL$
# $Id: 0cae9f95d9ed0841bbf77c91eef5f3d4c9a73f2e $
#
#***********************************************************EndPNNLCopyright*

# set -x

scriptPath0="${BASH_SOURCE[0]}" # works when script is sourced (unlike $0)
scriptPath=$(readlink -f "${scriptPath0}")
scriptCmd=${scriptPath##*/} # cf. $(basename ...)
scriptDir=${scriptPath%/*}  # cf. $(dirname ...)

#****************************************************************************

MG_XLIB_ROOT="${MG_XLIB_ROOT:-${scriptDir}/../../xlib/lib}"
MG_PERF_ROOT="${MG_PERF_ROOT:-${scriptDir}/../../xlib/perf}"

#-----------------------------------------------------------

perf="${MG_PERF_ROOT}/linux-5.5.9/tools/perf/perf"

#-----------------------------------------------------------

echo ${perf}

#****************************************************************************

zero=0
opt_period=0
opt_method=1
opt_buffer=8192

#****************************************************************************
# Parse arguments
#****************************************************************************

die()
{
    cat <<EOF 1>&2
${scriptCmd}: $*
Use '${scriptCmd} -h' for usage.
EOF
    exit 1
}

usage()
{
    cat <<EOF
Usage: ${scriptCmd} [options] [--] <app> [app-args]

Options:
  -h / --help   => print help
  -e / --event  => collection type for <pt-load> <pt-time> <ldlat> (def=pt-load)
  -b / --buffer => buffers size in bytes (def=8192)
  -p / --period => period for sampling ( 0 for full trace) (def=0)
  -o / --output => output folder name (def=<app>-trace-b<buffer>-p<period>
EOF
    exit 0
}

#-----------------------------------------------------------
# optional arguments
#-----------------------------------------------------------

while [[ $# -gt 0 ]] ; do

    arg="$1"
    shift # past argument

    case "${arg}" in
        -h | --help )
            usage
            ;;

        -e | --event )
            opt_method="$1"
            shift # past value
            ;;

        -b | --buffer-size )
            opt_buffer="$1"
            shift # past value
            ;;

        -p | --period)
            opt_period="$1"
            shift
            ;;

        -o | --output)
            opt_output="$1"
            shift
            ;;


        -- )
            break
            ;;

        * ) # beginning of <application> command line
            set -- "$arg" "$@"
            break
            ;;
    esac
done

#-----------------------------------------------------------
# required args
#-----------------------------------------------------------

if [[ -z $1 ]] ; then
    die "no command to monitor"
fi

#****************************************************************************
# 
#****************************************************************************

app=$@

IFS=' '
read -a strarr <<< "$app"
app_path=${strarr[0]}

IFS='/'
read -a strarr <<< "$app_path"
app=${strarr[-1]}
IFS=''


if [[ -z ${opt_output} ]] ; then
  opt_output="${app}-trace-b${opt_buffer}-p${opt_period}"
fi

mkdir ${opt_output}


#-----------------------------------------------------------
# launch
#-----------------------------------------------------------

out_fnm="${opt_output}/${opt_output}.perf"

printf "${scriptCmd}: collecting data for $bin with $args\n"


if [[ ${opt_method} =~ pt-* ]] ; then

    # mmap for perf's data:  -m
    # PT ring buffer size:   'aux-sample-size' in event
    # PT records ip for ptw: 'fup_on_ptw' in event
    # call graph:            -g + 'call-graph=lbr' in event
    # retired_loads:         umask=0x81,event=0xd0

    event_ptw="intel_pt/ptw=1,branch=0,period=1,fup_on_ptw=1/u"
    event_smpl=""
    
    opt_callpath="-g"
    opt_callpath_lbr=",call-graph=lbr"

    case "${opt_method}" in
        pt-load )
            event_smpl="cpu/umask=0x81,event=0xd0,period=${opt_period},aux-sample-size=${opt_buffer}${opt_callpath_lbr}/u"
            break
            ;;

        pt-time )
            event_smpl="ref-cycles/period=${opt_period},aux-sample-size=${opt_buffer}${opt_callpath_lbr}/u"
            break
            ;;

        * )
            die "invalid trace method '${opt_method}'"
            break
            ;;
    esac

    if (( ${opt_period} == ${zero} )) ; then
        ${perf} record -o "${out_fnm}" -m 4M,4M \
                -e ${event_ptw} -- "$@"
    else
        ${perf} record -o "${out_fnm}" -m 2M,2M \
                -e ${event_ptw} -e ${event_smpl} ${opt_callpath} -- "$@"
    fi

elif [[ ${opt_method} = 'ldlat' ]] ; then
    ${perf} record -o "${out_fnm}" -W -d \
            -e cpu/mem-loads,ldlat=1,period=${opt_period}/upp -- "$@"
fi



#-----------------------------------------------------------
# output directory
#-----------------------------------------------------------

cat <<EOF > ${opt_output}/memgaze.config
-p ${opt_period}
-m ${opt_method}
-b ${app_path}
-data ${opt_output}.perf
EOF

