#!/bin/bash
# -*- mode: sh -*-

#*BeginPNNLCopyright*********************************************************
#
# $HeadURL$
# $Id: 0cae9f95d9ed0841bbf77c91eef5f3d4c9a73f2e $
#
#***********************************************************EndPNNLCopyright*

 set -x

scriptPath0="${BASH_SOURCE[0]}" # works when script is sourced (unlike $0)
scriptPath=$(readlink -f "${scriptPath0}")
scriptCmd=${scriptPath##*/} # cf. $(basename ...)
scriptDir=${scriptPath%/*}  # cf. $(dirname ...)

#-----------------------------------------------------------

mg_anal="${scriptDir}/../libexec/memgaze-analyze-loc"

#****************************************************************************

opt_outDir=''
opt_trace_dir=''
trace=''

#****************************************************************************
# Parse arguments
#****************************************************************************

die()
{
    cat <<EOF 1>&2
${scriptCmd}: $*
Use '${scriptCmd} -h' for usage.
EOF
    exit 1
}

usage()
{
    cat <<EOF
Usage: ${scriptCmd} [options] 
Options:
   -h / --help   => prints help
   -o / --output => output directory path (optional)
   -tdir / --trace-dir => Directory for trace file & memgaze.config (required - used to locate trace file and stack address starting point)
   -t / --trace-file => Trace input file (required if trace_dir not specified - Default stack address 0x7f0000000000 used)
   -s / --spatial => Spatial correlational RUD analysis of contiguous hot regions ( 1 or 0 - Default 0 - no spatial analysis) 

EOF
    exit 0
}

#-----------------------------------------------------------
# optional arguments
#-----------------------------------------------------------
opt_outDir='.'
while [[ $# -gt 0 ]] ; do

    arg="$1"
    shift # past argument

    case "${arg}" in
        -h | --help )
            usage
            ;;

        -o | --output )
            opt_outDir="$1"
            shift # past value
            ;;
        
	      -tdir | --trace-dir )
            opt_trace_dir="$1"
            shift # past value
            ;;
	      -t | --trace-file  )
            opt_trace_file="$1"
            shift # past value
            ;;
	      -s | --spatial  )
            opt_spatial="$1"
            shift # past value
            ;;
    esac
done


#-----------------------------------------------------------
# required args
#-----------------------------------------------------------

trace=$opt_trace_file
if [[ $opt_outDir != '.' ]]; then
  mkdir $opt_outDir
fi

run_rud=" --zoomRUD --outputZoom ${opt_outDir}/rud.txt"

if [[ $opt_spatial == "1" ]] ; then
  run_spatial=" --spatial --outputSpatial ${opt_outDir}/spatial.txt"
fi

stack_addr=''
while IFS=' ' read -r type value; do
    echo "type: $type value: $value"
    if [[ $type == "-stack_start" ]] ; then
      stack_addr=$value
    elif [[ $type == "-t" ]] ;then
      trace=$value
    fi
done < ${opt_trace_dir}/memgaze.config 

spec_heap=''
if [[ $stack_addr != '' ]] ; then
  spec_heap=" --heapAddrEnd ${stack_addr}"
fi
#****************************************************************************
# 
#****************************************************************************
echo "Trace file ${trace}"

if [[ $trace == '' ]] ; then
  echo " Specify trace-file or trace-dir" 
else
  ${mg_anal} ${trace} --analysis --pnum 512 ${spec_heap} ${run_rud} ${run_spatial} 
fi




